#!/bin/bash

# Production Deployment Checklist

echo "=== Firebase Project Configuration ==="
echo "1. Create Firebase project at https://console.firebase.google.com"
echo "2. Enable Firestore Database (Start in production mode)"
echo "3. Enable Firebase Authentication"
echo "   - Enable Email/Password provider"
echo "   - Enable Google Sign-In provider"
echo "4. Create service account:"
echo "   - Go to Project Settings > Service Accounts"
echo "   - Click 'Generate New Private Key'"
echo "   - Save the JSON file securely"
echo ""

echo "=== Backend Configuration ==="
echo "Set these environment variables in Render:"
echo "  ENABLE_AUTH=true"
echo "  ALLOW_DEV_AUTH=false   # never enable the dev bypass in production"
echo "  USE_FIREBASE=true"
echo "  FIREBASE_PROJECT_ID=<your-project-id>"
echo "  GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json"
echo "  CLIENT_URL=https://your-frontend-domain.com"
echo "  NODE_ENV=production"
echo "  PORT=5000"
echo ""

echo "=== Frontend Configuration ==="
echo "Set these environment variables in Vercel (Vite requires the VITE_ prefix):"
echo "  VITE_API_URL=https://your-backend-url.render.com"
echo ""

echo "=== Firestore Security Rules ==="
echo "The rules are version-controlled in firestore.rules and firebase.json."
echo "Deploy them with:"
echo "  firebase deploy --only firestore:rules"
echo "The /users rule is owner-scoped (request.auth.uid == userId); the users"
echo "collection is NOT world-readable."
echo ""

echo "=== Deploy Steps ==="
echo "1. Push code to main branch"
echo "2. Deploy Firestore rules: firebase deploy --only firestore:rules"
echo "3. Verify /api/health endpoint returns 200 (it no longer reports auth mode)"
echo "4. Test auth flow with a Firebase ID token"
echo "5. Monitor Firestore for data writes"
echo ""

echo "=== Verification Checklist ==="
echo "□ Backend health check passes"
echo "□ Frontend loads and connects to backend"
echo "□ Firebase Auth login works"
echo "□ Chat messages save to Firestore"
echo "□ Leaderboard updates persist"
echo "□ User profiles save with auth UID and are owner-readable only"
echo "□ Mobile app builds with Expo EAS"
echo "□ End-to-end auth flow verified"
echo ""

echo "✅ Deployment checklist complete!"
